- docs/email-delivery.md
- load.php
Also provided this with a default so atleast we'll be able to send email when this is not configured
> Add email sending address setting

- inc/class-db.php
We are not getting db tracing currently as we are looking in the wrong namesapce for xray support
> Update NS reference for Xray

- inc/class-db.php
This is used in XRay etc for a top level stat
Requesting a pull to humanmade:master from humanmade:track-db-time
> Track overall time spent in database activity

- composer.json
- inc/namespace.php
Turns out it was a subproject before, which was broken, so I decided to put it on packagist and switch it to a real dep anyway.
> Fix memcached inclusion

- docs/email-delivery.md
- docs/limitations.md
> Fix docs links

- inc/class-db.php
- load.php
These are not under the Altis namespace.
> Fix XRay references

- docs/backups.md
- docs/dashboard.md
- docs/logs.md
- docs/vantage.md
Changing Vantage to Altis Dashboard.
> Update dashboard name and URL

- composer.json
This needs to be a release version.
> Update S3 Uploads version requirement

- docs/nginx-configuration.md
> FIx HM -> Altis naming

- docs/nginx-configuration.md
- inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php
- inc/audit_log_to_cloudwatch/namespace.php
- inc/cavalcade_runner_to_cloudwatch/namespace.php
- inc/namespace.php
- inc/ses_to_cloudwatch/namespace.php
- load.php
- Bug fix ensure cloud config is respected
- HM -> Altis typo in docs
- Coding standards fix
> Merge updates for 1.0.1

- docs/nginx-configuration.md
This could be reorganized to have more document hierarchy later on, but this example came up in Slack and having it spelled out explicitly may help future Altis developers. Snippet kindly provided by @nathanielks
> Document how to configure nginx to block a file

- docs/email-delivery.md
teeny-tiny type fix in Email Delivery Documentation.
> Typo fix - Email Delivery doc

- docs/README.md
- docs/https.md
- docs/page-caching.md
Changes docs content from BE to AE. (see https://github.com/humanmade/growth/issues/492)
> Docs: BE → AE

- inc/namespace.php
> Set SUBDOMAIN_INSTALL to false on install.php requests

- inc/namespace.php
Checks for the index being set or not, fixes issues when running PHPUnit.
> HTTP_USER_AGENT not set when running phpunit

- inc/class-db.php
> Remove unnecessary QM PHP variable gathering

- composer.json
\# Change Log
\## 1.2.0 - 2019-11-18
- Add Query Monitor Support [#36](https://github.com/humanmade/aws-xray/pull/36)
- Filter use of fastcgi_finish_request [#33](https://github.com/humanmade/aws-xray/pull/33)
- Redact password from POST requests, allow additional meta to be redacted via filters [#34](https://github.com/humanmade/aws-xray/pull/34)
- Fix composer.json license string [#38](https://github.com/humanmade/aws-xray/pull/38)
> Update AWS Xray to 1.2.0

- inc/namespace.php
Its cleaner to just change the bootstrap action hook
> Simplify cavalcade bootstrap on install

- composer.json
Fixes HM_DEPLOYMENT_REVISION undefined issue.
> Update x-ray to 1.2.1

- inc/namespace.php
Changes the bootstrap action hook
> Backport #91: Simplify Cavalcade bootstrap on install

- composer.json
> Backport #92: Update XRay to 1.2.1

- inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php
> Reduce how much we poll CloudWatch for Audit Log results

- inc/namespace.php
Current we send way too much data in `$_SERVER` in X-Ray requests, which is also potentially exposing data that we might not want to.
> R	emove extra data in xray requests

- assets/environment-indicator.css
- composer.json
- inc/environment_indicator/namespace.php
- inc/namespace.php
> Add menu and submenu to display ENV details

- assets/environment-indicator.css
- inc/environment_indicator/namespace.php
> Fix Twenty Twenty frontend display issue

- assets/environment-indicator.css
- inc/environment_indicator/namespace.php
Fixes #132 
@roborourke let me know if it's ok to keep in within the env indicator code? Otherwise, I'll move it into a separate folder (let me know the name of it).
> Add link to open support ticket from Altis menu

- dropins/batcache/advanced-cache.php
- dropins/batcache/batcache.php
We weren't able to apply this to `v3-branch`, so manually applying this way.
> Upgrade batcache to 1.3.2

- composer.json
Cavalcade 2.0.0 features the new pre flight filters, uses a more flexible `get_jobs_by_query()` method, better db indexes and better handling of the installation process.
> Update to cavalcade 2.0.0

- composer.json
- docs/specifications.md
- inc/namespace.php
Per the docs at https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-aws
> Add the EC2 Istance ID to AWS Xray traces

- inc/cloudwatch_error_handler/namespace.php
We got some renaming wrong when we did the HM -> Altis rename in this code.
> Fix error logger to CloudWatch

- composer.json
- docs/cdn-purge.md
- inc/cloudfront_media_purge/namespace.php
- inc/namespace.php
- load.php
- Creates a CloudFront invalidation request for deleted media on delete attachment.
> Cloudfront media purge

- assets/environment-indicator.css
In line with https://github.com/humanmade/altis-cms/pull/192
> Update CSS class name

- inc/healthcheck/namespace.php
> Changing to __healthcheck, changing json response

- composer.json
Fixes metadata (https://github.com/humanmade/aws-xray/pull/56) and segment details in Query Monitor (https://github.com/humanmade/aws-xray/pull/51).
> Update AWS X-Ray to 1.2.5

- composer.json
Should reduce the time to get patches out for the XRay plugin to our stacks.
> Update XRay to track patch version

- composer.json
> [Backport v3-branch] Update XRay to track patch version

- inc/healthcheck/class-cli-command.php
- inc/healthcheck/namespace.php
> Add Instance Healthcheck

- composer.json
- docs/cdn-purge.md
- inc/cloudfront_media_purge/namespace.php
- inc/namespace.php
- load.php
See https://github.com/humanmade/altis-cloud/pull/157
> Backport Cloudfront media purge v3

- composer.json
> [Backport] Update batcache to version 1.3.3

- inc/alloptions_fix/namespace.php
- inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php
- inc/audit_log_to_cloudwatch/namespace.php
- inc/cavalcade_runner_to_cloudwatch/namespace.php
- inc/class-db.php
- inc/cloudfront_media_purge/namespace.php
- inc/cloudwatch_error_handler/namespace.php
- inc/cloudwatch_logs/namespace.php
- inc/environment_indicator/namespace.php
- inc/healthcheck/cavalcade/namespace.php
- inc/healthcheck/class-cli-command.php
- inc/healthcheck/namespace.php
- inc/namespace.php
- inc/page_cache/namespace.php
- inc/performance_optimizations/namespace.php
- inc/ses_to_cloudwatch/namespace.php
- load.php
- wp-config.php
Fixes docblocks and adds file docblocks. This should prevent problems as our standards become stricter in future. It also makes the code style more consistent regarding alignment of array keys and parameter comments.
> Fix linter errors

- inc/alloptions_fix/namespace.php
- inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php
- inc/audit_log_to_cloudwatch/namespace.php
- inc/cavalcade_runner_to_cloudwatch/namespace.php
- inc/class-db.php
- inc/cloudfront_media_purge/namespace.php
- inc/cloudwatch_error_handler/namespace.php
- inc/cloudwatch_logs/namespace.php
- inc/environment_indicator/namespace.php
- inc/healthcheck/cavalcade/namespace.php
- inc/healthcheck/class-cli-command.php
- inc/healthcheck/namespace.php
- inc/namespace.php
- inc/page_cache/namespace.php
- inc/performance_optimizations/namespace.php
- inc/ses_to_cloudwatch/namespace.php
- load.php
- wp-config.php
I incorrectly used hyphens instead of a slash.
> Fix the @package names

- docs/email-delivery.md
- inc/namespace.php
- load.php
> Enable configuring email region

- inc/namespace.php
> [Backport v3-branch] Ensure Tachyon and Uploads URL use current site host name

- docs/build-scripts.md
This brings our docs up to date with the latest updates.
> Update build container package versions

- inc/namespace.php
Fixes uploads references on Local Server
> Allow use of alternate domain name for S3 on local

- inc/namespace.php
> Exclude ALB healthchecks from X-ray

- inc/class-db.php
> Send final filtered database query to X-Ray

- inc/namespace.php
- load.php
> Ensure no debug output in dev envs

- inc/elasticsearch_packages/namespace.php
> Check for existing package ID before removal

- inc/healthcheck/namespace.php
> Fix object cache method check

- inc/namespace.php
> [Backport v3-branch] Hotfix for the LudicrousDB plugin path

- inc/namespace.php
> Cache uploads directories by blog ID

- docs/dns-configuration.md
- docs/https.md
Currently we don't give many details around DNS configuration, and we also have a new requirement that custom SSL certs must include the project internal domain too.
> Add more docs on SSL and DNS configuration

- composer.json
[Changelog](https://github.com/humanmade/batcache/releases/tag/1.3.4):
- Optimize genlocks usage #19
> Update Batcache to latest version

- inc/namespace.php
Fixes https://github.com/humanmade/altis-cloud/issues/360
> Dont append port number for 80 or 443

- inc/namespace.php
Related to https://github.com/humanmade/altis-core/pull/130
> Add Cavalcade upgrade hook

- inc/namespace.php
> Fix LudicrousDB warnings

- docs/geo-targeting.md
Fixes #398.
Adds a link to the CF docs for the geolocation header.
> Update geo-targeting documentation

- composer.json
> Update to wp-redis v1.1.2

- inc/healthcheck/class-cli-command.php
- inc/healthcheck/namespace.php
- inc/namespace.php
> Allow instance healthcheck to run before WP or plugins load

- inc/healthcheck/class-cli-command.php
- inc/healthcheck/namespace.php
- inc/namespace.php
> [Backport v4-branch] Allow instance healthcheck to run before WP or plugins load

- docs/audit-log-storage.md
- docs/dashboard/logs.md
- docs/dashboard/x-ray.md
- docs/email-delivery.md
- docs/healthchecks.md
- docs/object-cache.md
- docs/page-caching.md
- docs/read-replica-database.md
- docs/s3-storage.md
- docs/scheduled-tasks.md
Extends the documentation to cover all cloud module features and integrations including relevant documentation of config and APIs.
Fixes #209
> Add docs for all missing Cloud config options

- tests/acceptance.suite.yml
- tests/acceptance/AdminCest.php
Requires https://github.com/humanmade/altis-dev-tools/pull/231
Fixes https://github.com/humanmade/product-dev/issues/839
> :white_check_mark: Check support ticket link works properly

- composer.json
Reverts humanmade/altis-cloud#490
> Revert "Update humanmade/aws-ses-wp-mail requirement from ~1.2.0 to ~1.3.0"

- inc/namespace.php
- load.php
> Use main network domain as from address

- inc/namespace.php
> Strip www. from default from mail address

- docs/https.md
I think my wording is a bit messy but really wanted to jot something down and open a PR for it before I forget. If you have a better one liner for HTTPs redirect please share!
> Add note about https redirection

- composer.json
Ref https://github.com/humanmade/docker-wordpress-php/issues/106
> Update aws-xray to 1.3.0 to support Excimer / PHP8

- composer.json
Related to issue https://github.com/humanmade/product-dev/issues/1017 and PR https://github.com/humanmade/batcache/pull/27
> Update version for batcache.

- docs/https.md
See https://github.com/humanmade/product/issues/453
> Modernize the HTTPS documentation

- docs/dashboard/teams.md
Fixes #646
Old
> In the below screenshot, we'll select the Altis Demo Instance.
New
> In the screenshot below, we'll select the Altis Demo Instance.
> Minor typo fix

- inc/healthcheck/cavalcade/namespace.php
Avoids db queries to cavalcade on each page load.
Fixes #668
> Move healthcheck schedule to altis migrate command

- inc/session_handler/class-disallowed-session-handler.php
> Ensure disallowed session handler class methods match parent class

- docs/specifications.md
Ref https://dashboard.altis-dxp.com/support/ticket/7744/
> Clarify php max execution time

- docs/build-scripts/README.md
Add nvm installation example to stress on the need to install it and that it is not preloaded.
> Add nvm installation example

- composer.json
- c8ae86a - Update batcache requirement to 1.5.1
> Update batcache requirement to 1.5.1

- docs/build-scripts/README.md
> Backport 746 to v15-branch

- composer.json
- inc/namespace.php
- inc/session_handler/class-wp-cache-session-handler.php
We don't have a solution for Sessions yet, we could still use predis for that if we wanted.
See https://github.com/humanmade/product/issues/567
Fixes #748
> Add support for Afterburner

- composer.json
See: https://github.com/humanmade/ludicrousdb/pull/8
> Update LudicrousDB to 5.0.6

- docs/afterburner-cache.md
- docs/afterburner.md
- docs/architecture.md
Mention it in the architecture page.
(Note modified lines have been reformatted to MD standard)
Fixes https://github.com/humanmade/product-dev/issues/1354
> Add documentation for Afterburner.

- docs/dns-configuration.md
Fixes issue https://github.com/humanmade/altis-cloud/issues/805
> Fix image paths in DNS configuration page

- docs/afterburner.md
Reformatted file to standards.
Fixes https://github.com/humanmade/altis-documentation/issues/538
> Add instruction to enable Afterburner

- composer.json
Address issue https://github.com/humanmade/product-dev/issues/1507
> Update to latest hm/wp-redis version

- inc/afterburner/class-qm-collector.php
- inc/afterburner/class-qm-output-html.php
- inc/afterburner/namespace.php
- inc/namespace.php
- Add Afterburner panel to QM
- esc_html
- Return param
- phpcs
> [Backport v18] Add Afterburner panel to QM

- inc/afterburner/class-qm-collector.php
- inc/afterburner/class-qm-output-html.php
- inc/afterburner/namespace.php
- inc/namespace.php
- Add Afterburner panel to QM
- esc_html
- Return param
- phpcs
> [Backport v17] Add Afterburner panel to QM

- docs/build-scripts/private-dependencies.md
- docs/variables-secrets.md
Fixes https://github.com/humanmade/altis-cloud/issues/876
> Add documentation for variables and secrets

- docs/email-delivery.md
Merges PR https://github.com/humanmade/altis-cloud/pull/888 in to Master branch
> Backport docs change from v19-branch

- inc/session_handler/class-disallowed-session-handler.php
Updated return types to match the implemented interface. 
Also updated parameter names to match the interface.
Fixes https://github.com/humanmade/product-dev/issues/1612
> Fix deprecation warning.

- docs/database.md
- docs/specifications.md
Remove reference to MySQL 5.7 in docs.
Fixes https://github.com/humanmade/altis-local-server/issues/721
> Issue 721 Remove support for MySQL 5.7

- inc/cavalcade_runner_to_cloudwatch/namespace.php
This should reduce the calls to 1 from 9.
> Reduce number of API calls to PutMetricData

- docs/specifications.md
Update the list of PHP version  mentioned in the specifications page.
Addresses https://github.com/humanmade/altis-documentation/issues/417
> Update PHP versions in specifications

- docs/build-scripts/README.md
Update the versions of the tools that are pre-installed in the build container for the build scripts.
The versions were derived from directly querying the tools in a built version of the container.
> Update tool version information.

- docs/audit-log-storage.md
Add a note about the retention policy of audit logs in cloud storage
Fixes https://github.com/humanmade/altis-security/issues/377
> Update audit log docs

- docs/https.md
Backport https://github.com/humanmade/altis-cloud/pull/958 to v19 branch
> Backport 958 to v19 branch

- docs/page-caching.md
- Delivers https://github.com/humanmade/altis-cloud/issues/948
> Updating page-caching.md to include the new query params in exclusion list 

- docs/cli/README.md
Fixed some typos, and linting issues.
Addresses https://github.com/humanmade/product-dev/issues/1811
> Updated docs for the new ESM version.

- .github/ISSUE_TEMPLATE/1-bug-report.yml
- .github/ISSUE_TEMPLATE/2-documentation.yml
- .github/ISSUE_TEMPLATE/3-feature.yml
- .github/ISSUE_TEMPLATE/config.yml
- inc/namespace.php
Add Standard Issue templates
This PR adds standard issue templates to the repo.
Follows on from https://github.com/humanmade/product-dev/pull/1842
> Add Standard Issue templates

- docs/usage.md
Backport https://github.com/humanmade/altis-cloud/pull/990 to v23 branch.
> Backport PR #990 to v23 branch
