humanmade/altis-cloud

load.php

This changes the configuration to be more granular, and only turns off the non-production parts of the configuration. This ensures things like Redis work locally.

Turn module on for all environments

---

inc/namespace.php

As per the code comment, we don't define this in the infra in ECS or EC2

Define TACHYON_URL in cloud module

---

plugins/healthcheck/inc/namespace.php

Currently we don't pass the `Accept` header to the origin via the CDN, for cache performance reasons. This is unlikely to change soon, so I added support for specifying it via a query param.

Allow overriding Accept with `_accept=json`

---

load.php
wp-config.php

Per https://github.com/humanmade/platform-dev/issues/323, we are screwing up any inclusion of autoload.php outside of the wp-config.php. We're discussing a better long term solution in https://github.com/humanmade/platform-dev/pull/325, but this is intended to get things functioning.

Add check for add_action

---

composer.json

We don't want to be relying on a floating version of these.

Switch deps from dev-master

---

inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php
inc/audit_log_to_cloudwatch/namespace.php
inc/namespace.php
load.php

Initially this was part of the security module, but I think it actually makes a lot more sense here. This switches out the Stream DB provider for AWS CLoudWatch Logs in the cloud environments.

Audit Log to CloudWatch

---

inc/namespace.php
load.php

Currenly we only support the ECS infrastructure, but I think given it's not much to add, we should also support the EC2 infra. Without that, we are goign to need to wait to migrate all clients to ECS before they can use Altis, which I think is going to be a hold-up for many trying it out.

Support EC2 infra.

---

inc/namespace.php

I think for subtle reasons, and practically, it's better not to have these available.

Remove install plugins / themes in Cloud environments

---

inc/namespace.php
load.php

Currently we define `WP_CACHE` on `enable_wp_debug_mode_checks`, which is too late -- defualt constants are already loaded setting WP_CACHE to `false`.

Fix batcache via define

---

inc/namespace.php

As discussed we'll use priority 0 for any plugins loaded via modules.

Update muplugins_loaded action priority

---

inc/namespace.php

I thought this was already the case, turns out it is not. `admin-ajax.php` is often used as a quick HTTP API to power the front-end of the site for features like pagination, and we want to be caching all those requests like any other.
Fixes #34.

Cache admin-ajax requests for logged out users

---

composer.json

- Use shutdown hook instead of register_shutdown_runction #32

Update AWS Xray to Version 1.1.3

---

inc/namespace.php

Adds checks to ensure the following configuration options are respected:
* `ludicrousdb`
* Either `redis` or `memcached` are enabled before loading object caching
* Logic check of `email-from-address` to ensure it's set and not falsey
Additionally I am unsure whether 
* `bootstrap()` should return early if `! $config['enabled']`
* `SES_To_CloudWatch\bootstrap();` and `CloudWatch_Logs\bootstrap();` should be conditional on `audit-log-to-cloudwatch || php-errors-to-cloudwatch`.

Ensure Cloud configuration is respected.

---

docs/page-caching.md

• Fix typo
• Switch HM reference to Altis support
Closes #53

Fix typo in page cache cookie example and change HM reference to Altis support

---

inc/class-db.php

In https://github.com/humanmade/terraform-app-stack/pull/206 we are not using tls for the mysql connection, so we don't need to use persistent connections.

Don't use persistent MySQL connections

---

docs/build-scripts.md
docs/geo-targeting.md
docs/limitations.md
docs/logs.md
docs/page-caching.md
wp-config.php

This PR eliminates all appearances of the string `HM Cloud` (case-sensitive) in favour of `Altis`.
Didn’t touch any code; docs and 1 comment in wp-config.php only.

Fix branding

---

dropins/batcache/composer.json

Using this as a mu-plugin will put it into the wrong location for Altis.

Change package type to library

---

inc/class-db.php

LudicrousDB doesn't provide the `dbname`, `dbuser` etc instance vars on the `global $wpdb` object, which is needed by WP CLI (and some others) to detect what the DB name is. This is used when getting a list of tables for example, which breaks with LudicrousDB. Also, search-replace commands also break unless passed the `--all-tables` flag.
LudicrousDB doesn't set these almost for a good reason: each host you add to LudicrousDB _could_ use a different database name, so there is no "single" DB name, hence no setting of an instance variable for `dbname`. Instead, I decided to go for a better default: if a database host is configured that has `write` properties, then use that one as the host (etc) references in the instance variables.

Backport: Set the DB `dbname` etc properties

---

inc/page_cache/namespace.php

Redirects are not currently being cached and have the potential for bringing down a site. Let's fix that!

Enable batcache redirect caching

---

inc/healthcheck/inc/cavalcade/namespace.php
inc/healthcheck/inc/namespace.php
inc/namespace.php
inc/performance_optimizations/namespace.php

Checking for REQUEST_URI early in the cloud module breaks in contexts where `$_SERVER['REQUEST_URI']` is not set

Check for REQUEST_URI before using in healthchecks

---

inc/namespace.php

Fixes https://github.com/humanmade/altis-cloud/issues/77.
We discovered in some cases the fixes in https://github.com/humanmade/altis-cloud/pull/73 did not adequately prevent errors during healthchecks. Specifically, when `$wpdb` sets the blog prefix, it checks if `MULTISITE` is set and when not follows the standard `{prefix}_{blog id}_table` pattern. This PR sets `MULTISITE` in order to prevent this issue.
Of note is whether or not we should set it to `true` or `false`. We currently detect `WP_INSTALLING` and conditionally set `MULTISITE` if `WP_INSTALLING` is _not_ defined, which makes me think we need to set this to `false` to prevent any weirdness.

Set MULTISITE to prevent $wpdb from setting the database table prefix incorrectly

---

load.php

This changes the default for X-Ray to be enabled in all environments, not such ecs and ec2. This is because X-Ray is now used in the Dev Tools too.
See https://github.com/humanmade/altis-dev-tools/issues/23

Enable X-Ray always

---

inc/class-db.php

Adds support into our custom DB drop-in for Query Monitor, which provide richer information about database queries, including a full trace and row information. It also allows breaking down queries by component, and rich error data.
Fixes #84.
Before | After
-- | --
Error Before | Error After
-- | --
cc @johnbillion - it'd be neat if the data collection part could be abstracted in QM so this is less brittle if you ever need to change the DB drop-in code.

Add support for Query Monitor to DB drop-in

---

composer.json
inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php
inc/cavalcade_runner_to_cloudwatch/namespace.php
inc/healthcheck/cavalcade/namespace.php
inc/healthcheck/class-cli-command.php
inc/healthcheck/inc/namespace.php
inc/healthcheck/namespace.php
inc/healthcheck/plugin.php
inc/namespace.php
inc/ses_to_cloudwatch/namespace.php

Let's fix up these dumb errors.
Main BC change is that `Altis\Healthcheck` is now `Altis\Cloud\Healthcheck`. Our modules interact with it via a filter, not directly, so shouldn't have an impact.

Fix coding standards

---

inc/namespace.php

Cavalcade was trying to set its db option before the tables had been created, and the healthcheck shouldn't run on install.

Prevent plugins trying to set options early

---

.github/workflows/backport.yml

The backport app has been retired and is now a github action.

Add the backport action

---

composer.json

Addresses the issue of cavalcade tables being created with server default charset and collation rather than utf8mb4

Update Cavalcade to 1.0.1

---

composer.json

Changelog:
- Fix max_age being set to 1 on Batcache HIT humanmade/batcache#13
--
This will need manually backporting to v2-branch too.

Update batcache to 1.3.2

---

inc/namespace.php
inc/page_cache/namespace.php

Fixes #114 
I'm guessing the function should live in the `Altis\Cloud\Page_Cache` namespace.

Fix warning through for `disable_no_cache_headers_on_admin_ajax_nopriv()`

---

assets/environment-indicator.css
inc/environment_indicator/namespace.php

Env indicator: Use altis blue instead of aqua

---

wp-config.php

This will avoid an issue when trying to prepend `wordpress/wp-includes/plugin.php` early before any scripts in `vendor/bin/` are called. This allows us to document a supported method for running `phpunit` for instance against Altis <= v2.

Check Altis\ROOT_DIR is defined

---

inc/namespace.php
load.php

Log remote requests made by the AWS SDK

---

inc/namespace.php

During installation the workaround we had previsously actually stopped the Cavalcade tables being created at all after the improved handling of that in 2.0.0 was added.

Error on install after updates to cavalcade 2.0.0

---

composer.json

Reverts humanmade/altis-cloud#150
I screwed up by adding a merge commit - going to do a fresh easily backportable commit to update it to `~1.2.7`

Revert "Update AWS X-Ray to 1.2.5"

---

inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php

Follow up to https://github.com/humanmade/altis-cloud/pull/97.
This limits the request rate to CloudWatch when checking if queries are complete.

Reduce polling on CloudWatch in Audit Log results

---

inc/cloudwatch_error_handler/namespace.php

It turns out when the CloudWatch Error Handler was active, we'd basically call `fastcgi_finish_request` as soon as > 100 errors were caught. This meant requests could randomly return 200 responses with no body.
This is an important fix to backport as far back as we can!

Only call fastcgi_finish_request on shutdown

---

inc/page_cache/namespace.php

This will allow developer to add `unique` based on query string or any dynamic conditions.
We can also add filter for the same.

Fix page cache to allow dynamic unique param

---

inc/class-db.php

Currently `wpdb::bail` will not `exit` if `wpdb->show_errors` is set to `false`. This can be the case in several situations, such as Query Monitor being enabled. Also, the default `wpdb::bail` implementation use `wp_die` which reads form the database, causing a circular call loop in some cases.
We don't need to ever no-exit on a database bail call.

Add wp-db bail override

---

inc/healthcheck/namespace.php
inc/namespace.php

ElasticSearch is no longer solely used for search, rather it is a core service of the infrastructure and therefore the cloud module.
This PR replicates the request signing, error logging and healthcheck from the search module in a back compatible way.
Currently if the search module is not enabled then ES requests for analytics data for example will fail. This is definitely a bug that needs to be addressed.
Fixes #187

Move ES request signing to Cloud Module

---

inc/healthcheck/namespace.php
inc/namespace.php

Backporting #188
-------------
Move ES request signing to Cloud Module
ElasticSearch is no longer solely used for search, rather it is a core service of the infrastructure and therefore the cloud module.
This PR replicates the request signing, error logging and healthcheck from the search module in a back compatible way.
Currently if the search module is not enabled then ES requests for analytics data for example will fail. This is definitely a bug that needs to be addressed.
Fixes #187

[Backport v3-branch] Move ES request signing to Cloud Module

---

inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php

Turns out that in-progress query responses have initial results already in the response, which I didn't realize. In cases when we are searching most-recent, we can assume once the results hits the limit, the results set will not change.
To keep total found rows accurate, I have put a 15 second limit when using this performance optimization. Though we might get the most recent 20 results in 2 seconds, we let it take u pto 15 seconds to fully complete, so we can get accurate totals counts.

Short-circuit Audit Log requests when they have enough data.

---

docs/cdn-purge.md
inc/namespace.php

Replaces #196. See #186.
This goes further and enforces a maximum of 10 items per HTTP request. This is designed to be lower than the wildcard limit (15) in CloudFront, and is mainly designed to detect use of the function in loops, which is dangerous.

Enforce purge limitation

---

inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php

There was an error in the backport of https://github.com/humanmade/altis-cloud/pull/194 which causes a fatal when tryign to view the audit log. This broke Altis/cloud 3.0.9 and 3.0.10.

Fix cloudwatch_logs_client reference

---

inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php

In cases where StopQuery fails, we don't want the exception to bubble, as it is non-essential.

Catch exceptions from StopQuery in CloudWatch

---

inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php

In cases where StopQuery fails, we don't want the exception to bubble, as it is non-essential.
See #202

Backport v3: Catch exceptions from StopQuery in CloudWatch

---

inc/namespace.php

Fetching EC2 instance metadata spits out an error on local environments. This was never spotted until #210 got merged and fixed the status check.

Check architecture when adding ec2 metadata

---

inc/namespace.php

Currently we define the S3 Uploads bucket URL at the infrastructure level, eg. `example.altis.cloud/uploads`.
Once the site has been migrated to its production URL the infra level setting is still used. Ideally it should change to match the URL set in the database.
This update ensures the S3 bucket URL and Tachyon URL use the main site host name for all sub domain and sub directory sites, and if a subsite has a custom domain ensures it uses that.
Fixes #217

Ensure Tachyon and Uploads URL use current site host name

---

inc/namespace.php

PHP can be run via the command line directly and not just WP CLI - we need to account for that case too as currently when running unit tests the install step will cause XRay to spit out some unnecessary warnings.

Don't load XRay on all CLI invocations

---

inc/namespace.php

We have this check in all the other uses, just not this one.
Fixes #231.

Check ELASTICSEARCH_HOST definition before use

---

inc/cloudwatch_logs/namespace.php
tests/class-test-cloudwatch-logs.php

In cases when the sequence token in the cache is wrong, we can auto-retry with the new sequence token.
I also added unit tests here, which I'm running from the main platform-dev repo. I will share my approach on that, but in the mean time I don't see an issue per-say with including the unit tests already.
Fixes #168.

Fix InvalidSequenceToken in CloudWatch Logs

---

docs/dashboard/logs.md

This fixes the broken link to `docs/dashboard`.
Note that this needs to be backported to v4 & v5.

Doc: Fix link to dashboard

---

composer.json

Fixes unicode site names in sender header
Fixes #247

Update AWS SES mail to 1.2.0

---

composer.json

Fixes unicode site names in sender header
Backporting #264

[Backport v3-branch] Update AWS SES mail to 1.2.0

---

inc/environment_indicator/namespace.php

The node is registered from the branding module, If the branding module is disabled then this node does not exist
Fixes #236

Add an arbitrary node if the node does not exist in

---

inc/cloudwatch_error_handler/namespace.php

Looks like this was a regression introduced with the addition of `fastcgi_finish_request()` added to the shutdown function for sending cloudwatch errors. This is the actual fix for https://github.com/humanmade/altis-dev-tools/issues/113
There is an additional PR here to reinstate full Query Monitor capabilities in cloud environments https://github.com/humanmade/altis-dev-tools/pull/116

Fix Query Monitor output in cloud

---

composer.json

The official package has some recurring issue of tags being deleted. This has happened repeatedly and means Altis cannot be installed so we need to move this into our direct control.

Switch to HM fork of Ludicrous DB

---

composer.json

The official package has some recurring issue of tags being deleted. This has happened repeatedly and means Altis cannot be installed so we need to move this into our direct control.
Backporting #293

[Backport v3-branch] Switch to HM fork of Ludicrous DB

---

inc/namespace.php

This was dumb and I am dumb and this does literally nothing because you cannot read response headers client side without making the request from JS itself.

Remove reflect cloudfront headers function

---

inc/namespace.php

Prevents cache thrashing by repeatedly switching to and back from the main blog when building Tachyon URLs for attachments in multisite subsites.
See #312 - work in progress, opening pull request to test only.

Cache S3 upload dirs

---

inc/namespace.php

Ugh, I'm sorry here. :facepalm: 
I didn't fully test after the last commit in #313, and ended up breaking the whole Media Library.
If the second argument passed into `path_join()` has a leading slash, WP will treat it as an absolute path and just return it unchanged. So `Altis\Cloud\get_main_site_url( '/2020/02/19/yolo.gif' )` just returns '/2020/02/19/yolo.gif', rather than a fully qualified Tachyon URL.
This fixes that problem by removing the leading slash.

Fix path_join bug introduced in #313

---

inc/namespace.php

Our vantage-backend servers don't have APCU loaded, so this causes X-Ray to crash currently.

Only use APCU if loaded

---

composer.json

Makes Altis Cloud PHP 7.4+ compatible.
Fixes #314

Update minimum S3 Uploads version

---

inc/namespace.php

In some instances WP does not check the writability of the file system when showing parts of the UI, notably the Updates screen in Network Admin.
Fixes #347

Set disallow file mods constant on cloud environments

---

inc/performance_optimizations/namespace.php

REST API uploads time limits were not previously bumped, related to the nginx config update.

Increase time limit for REST API uploads

---

inc/healthcheck/namespace.php
inc/namespace.php

This is an effort to make the healthcheck backwards compatible in case wp-redis changes the stats method behaviour.

Fix redis healthcheck

---

inc/elasticsearch_packages/namespace.php

The `wp_next_scheduled()` response appears to be subject to caching so for custom cron job intervals such as 1 minute in this case the next scheduled time can be too old for it to ever match the actual next event. This means the current method for clearing the scheduled task fails silently.
Using clear scheduled hook is more appropriate here because it is the arguments that are unique to the task.
Fixes #379

Use clear scheduled hook to remove package status check

---

inc/healthcheck/namespace.php

Replaces the Human Made logo with the Altis logo in the healthcheck component.
I'm not sure where this logo/page is actually located or how it's accessed. I don't see anything locally or on on platform-test at the `domain.com/healthcheck/` endpoint and I don't see anything in Vantage either, so I can't actually test/confirm that this is working, in the off chance that there's another place the logo is used.
Fixes #151

replace the hm logo with the altis logo

---

inc/namespace.php

Fixes #421.
Also now activated on all environments to ensure consistency. This will cause the uploads URL on Local Server to change from (eg) `https://s3-altis-dev.altis.dev/uploads` to `https://altis-dev.altis.dev/uploads`.

Fix early uploads bad usage

---

assets/environment-indicator.css
docs/dashboard/x-ray.md
inc/namespace.php

This allows viewing the request trace directly, useful if you're on production without the dev tools enabled.

Link directly to the X-Ray trace

---

inc/elasticsearch_packages/namespace.php

Follow on from #455
Allows immediate update of indexes if using inline index settings, the AWS ES package creation remains the same but does not control when the reindexing occurs as there are not used during indexing or updating settings in inline mode.

Don't wait for AWS ES package creation when using inline index settings

---

inc/namespace.php

Multisite functions are not available during the initial install.

Check if this is intial install before using `get_network()`

---

docs/page-caching.md

By default Batcache is not on local environments. For developing cache customizations locally, you may wish to enable Batcache for local environments.
The example in the documentation is `"batcache": false`, where it should be `"batcache": true`.

Correction to the configuration documentation

---

inc/healthcheck/namespace.php

We recently ran into a case when notoptions was very large, I don't believe there's a good reason these cache keys should be so large.

Healthchecks for alloptions / notoptions sizes

---

composer.json

Adds the tilde version constraint as well.

Update Ludicrous DB to 5.0.1

---

composer.json

Backporting #557
---------------
Updates the requirements on [humanmade/ludicrousdb](https://github.com/humanmade/ludicrousdb) to permit the latest version.
- [Release notes](https://github.com/humanmade/ludicrousdb/releases)
- [Commits](https://github.com/humanmade/ludicrousdb/compare/5.0.1...5.0.2)
---
updated-dependencies:
- dependency-name: humanmade/ludicrousdb
dependency-type: direct:production
...

[Backport v9-branch] Update humanmade/ludicrousdb requirement from ~5.0.1 to ~5.0.2

---

docs/architecture.md

This should fix the diagram URL mapping; it's not currently getting updated to be a proper URL.

Fix architecture diagram URL

---

inc/class-db.php

When a database query results in an error, the generic `qmdb` error code is shown in Query Monitor instead of the actual error code from MySQL. This is because the reference to `mysqli` isn't namespaced correctly.
Before:
After:

Correct the reference to `mysqli` so database error code appears correctly in QM

---

docs/scheduled-tasks.md

The check that prevents duplicate events from being scheduled only affects one-off events (the check only exists within `wp_schedule_single_event()`. This documentation change clarifies that.

Clarify the duplicate cron event check

---

docs/specifications.md

Ref https://github.com/humanmade/docker-wordpress-php/issues/106

Update docs to remove v8js and xhprof from available modules list

---

inc/namespace.php

Original issue - https://github.com/humanmade/altis-cloud/issues/621
Current URL format is: `https://dashboard.altis-dxp.com/#/<region>/<environment>/xray/trace/<trace>`
Suggested URL format is : `https://dashboard.altis-dxp.com/#/e/<environment>/xray/trace/<trace>`

Correct the debug url in the Altis dashboard.

---

inc/namespace.php

Currently XRay is bootstrapped only if XHProf is available, which we no longer build for PHP 8.0 and above. The upstream XRay plugin supports the newer Excimer profiler that is PHP 8.0+ compatible. This change bootstraps the plugin if either of the two profilers is available.

Bootstrap XRay if Excimer is available

---

inc/class-db.php

Originally identified in - https://github.com/humanmade/altis-documentation/pull/425
---
Running `composer dev-tools codecept -p  packages/documentation/tests run -vvv` I was able to identify the first error:
```php
PHP Fatal error:  Uncaught Error: Undefined constant "Altis\Cloud\SAVEQUERIES" in /usr/src/app/packages/cloud/inc/class-db.php:63
```
After applying the fix for it, the following error came up:
```php
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /usr/src/app/packages/cloud/inc/class-db.php:69
```
Applying the two fixes above allows `composer dev-tools codecept -p  packages/documentation/tests run -vvv` to run smoothly.

Ensure `SAVEQUERIES` is defined before checking its value

---

docs/build-scripts/README.md

I see that nvm is being installed and used in the deploy script on several projects where the included asdf could just be used instead. This clarifies the docs in that regard.

Clarify asdf and nvm

---

composer.json
inc/namespace.php
inc/session_handler/class-wp-cache-session-handler.php

Adds support for PHP sessions with our Afterburner implementation of the WordPress object cache.

Add a WP Cache session handler

---

docs/limitations.md
docs/scheduled-tasks.md

Updated confusing placement of infrastructure limitation link. Add link to Cavalcade page from infrastructure page.

Updates to Cavalcade and Infrastructure pages

---

composer.json

Contains the fix for persistent sockets corruption.

Update wp-redis-predis-client to 0.1.1

---

inc/cavalcade_runner_to_cloudwatch/namespace.php

We recently enabled `opcache.enable_cli` so Cavalcade Runner now has the opcache enabled. This is a bug, it turns out in the opcache whereby including files over and over again will lead to a memory leak. See https://github.com/php/php-src/issues/9812 for details.
This bug causes a very large memory leak in Cavalcade Runner because we naively re-init the Cloudwatchclient on every call to put_metric_data() etc.
So, it makes sense to only create the cloudwatch client once. THis should also drastically reduce the impact of the PHP bug.

Fix cavalcade runner memory usage leak

---

inc/cloudfront_media_purge/namespace.php

CloudFront will return an error from `createInvalidation` if the URL is not encoded. `tachyon_url()` already does this internally, so is not an issue on the tachyon_url.

URL encode filenames in CDN Media Purge

---

inc/afterburner/class-qm-collector.php
inc/afterburner/class-qm-output-html.php
inc/afterburner/namespace.php
inc/namespace.php

Add Afterburner panel to QM

---

inc/namespace.php

This is needed to support the newer `presign` query param functionality added in https://github.com/humanmade/tachyon-plugin/releases/tag/0.11.8

Set the TACHYON_SERVER_VERSION

---

inc/namespace.php

In #863 we assume that TFA_VERSION is defined but we never actually define it. This change defines the constant from the environment variable.

Define TFA_VERSION from env vars

---

inc/afterburner/namespace.php

Core 6.5.0+ introduced new translation classes and routines, removing the need for (and use of) the MO object, which Afterburner pomo relies on. This change brings back the old behavior when loading text domains.
See: https://github.com/humanmade/product-dev/issues/1546

Fix Afterburner translations with WordPress 6.5.0

---

inc/session_handler/class-disallowed-session-handler.php

Union return type was only added in 8.0. So this fails the hm-linter checks

Fix < php 8.0

---

docs/page-caching.md

We should clarify exactly how the cookie caching behaviour works, as this can potentially be confusing.

Specify cookie cache overrides

---

inc/elasticsearch_packages/namespace.php
inc/healthcheck/namespace.php
inc/namespace.php

This change corrects the spelling of Elasticsearch. 
Fixes https://github.com/humanmade/product-dev/issues/1644

Fixes spelling of Elasticsearch.

---

inc/cavalcade_runner_to_cloudwatch/namespace.php
inc/namespace.php

Currently we're buffering up to 1,000 log entries (with a max of 24 hours) for cavalcade logs which makes a significant delay in them appearing in the Altis Dashboard.
This doesn't change the cost of PutLogEvents which is based off event count, regardless of whether they are in separate API calls or not.
Fixes https://github.com/humanmade/product-dev/issues/1664

Flush Cavalcade Logs every job

---

inc/audit_log_to_cloudwatch/class-cloudwatch-driver.php

Calculating the column values is very slow and mostly leads to timeouts on loading the page. Having the column values just improves the UI slightly by greying out values that are not in the DB. It doesn't stop the `<select>` from showing all filter options.
I added this as a filter incase anyone would still want this functionality.

Disable loading column values in audit log by default

---

docs/dns-configuration.md

Clarifies some aspects of the DNS configuration. Adds a reference to the launching guide and clarifies use of ANAME/ALIAS records.
Addresses: https://github.com/humanmade/altis-documentation/issues/435

Add additional help to DNS configuration guide

---

composer.json
inc/namespace.php

Now that the Pantheon Systems original `wp-redis` is available from [packagist.org](https://packagist.org/packages/pantheon-systems/wp-redis), we can switch to using it.
Fixes https://github.com/humanmade/altis-cloud/issues/866

Switch to upstream wp-redis

---

composer.json

Includes https://github.com/humanmade/wp-redis-predis-client/pull/14 which will show when cache flushes happen

Update Predis adaptor to 0.1.2

---

inc/namespace.php

When turning off elasticsearch for local server, ensure we don't try to reference the host.
Addresses https://github.com/humanmade/altis-local-server/issues/257

Remove warning when elasticsearch is turned off

---

inc/cavalcade_runner_to_cloudwatch/namespace.php

Fixes https://github.com/humanmade/product-dev/issues/1709
---
Does this PR meet our definition of done? See [the Play Book Definition of Done](https://playbook.hmn.md/play/product/definition-of-done-2/)

Remove job level cavalcade metrics

---

docs/https.md

The link to DNS Configuration on https://docs.altis-dxp.com/cloud/https/ is broken as it is missing the `/cloud` portion of the URL. Comparing to other pages at the same level (eg. https://docs.altis-dxp.com/cloud/afterburner/), looks like the link should just have one `.`.

Fix link to DNS Configuration docs

---

docs/https.md

Backport of https://github.com/humanmade/altis-cloud/pull/954 to master.
The link to DNS Configuration on https://docs.altis-dxp.com/cloud/https/ is broken as it is missing the /cloud portion of the URL. Comparing to other pages at the same level (eg. https://docs.altis-dxp.com/cloud/afterburner/), looks like the link should just have one `.`
Hat tip to @sambulance for the fix.

Backports fix 954 to master

---

docs/dns-configuration.md

Adds a note to the domain configuration documentation to clarify the case for subdomains.
Fixes: https://github.com/humanmade/altis-cloud/issues/759

Add subdomain entry instructions to domain docs

---

load.php

- Delivers https://github.com/humanmade/altis-cloud/issues/948
In the above issue, we are adding three more parameters (dclid, gclid, and twclid) to the cache key exclusion list to avoid cache sharding

Adding dclid, gclid, and twclid to the default exclusion list

---

docs/specifications.md

Bugbear of mine. This sort of information reads better when displayed newest to oldest.

Order PHP information from newest to oldest.

---

inc/elasticsearch_packages/namespace.php

Action `altis.search.check_package_status` passes 4 arguments to the hooked function.
Fixes issue https://github.com/humanmade/altis-cloud/issues/644

Fixes the argument count for hook
